language: node_js

node_js:
  - 14

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test:coverage && cat ./coverage/lcov.info | coveralls

deploy:
  provider: heroku
  app: landing-page-tf
  api_key: $HEROKU_API_KEY
